- name: Update apt cache and install MySQL
  apt:
    update_cache: yes
    name:
      - mysql-server
      - python3-pymysql
    state: present

- name: Allow MySQL to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^bind-address"
    line: "bind-address = 0.0.0.0"
  notify: Restart MySQL

- name: Ensure MySQL service is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create WordPress database
  shell: mysql -e "CREATE DATABASE IF NOT EXISTS {{ mysql_db_name }};"
  become: yes
  become_user: root
  changed_when: false

- name: Create MySQL user for WordPress with Docker subnet access
  shell: mysql -u root -e "CREATE USER IF NOT EXISTS '{{ mysql_user }}'@'{{ mysql_container_subnet }}' IDENTIFIED BY '{{ mysql_password }}'; GRANT ALL PRIVILEGES ON {{ mysql_db_name }}.* TO '{{ mysql_user }}'@'{{ mysql_container_subnet }}'; FLUSH PRIVILEGES;"
  changed_when: false
